# Generated by Django 3.2.6 on 2021-09-29 12:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('author', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Addictions', 'Addictions'), ('Autism', 'Autism'), ('Anxiety', 'Anxiety Disorders'), ('Bipolar', 'Bipolar Disorder'), ('Depression', 'Depression'), ('PTSD', 'Post-Traumatic Stress Disoder (PTSD)'), ('Personality', 'Personality Disorders'), ('Sexual', 'Sexual Disorders'), ('General', 'General')], default='Addictions', max_length=12)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychologists', models.CharField(choices=[('Alice', 'Alice Gathoni'), ('Peterson', 'Peterson Omollo '), ('Joram', 'Joram Karanja'), ('Mary', 'Mary Manders'), ('Newton', 'Benard Newton'), ('Katherine', 'Katherine Muthoni')], default='Alice Gathoni', max_length=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('Addictions', 'Addictions'), ('Autism', 'Autism'), ('Anxiety', 'Anxiety Disorders'), ('Bipolar', 'Bipolar Disorder'), ('Depression', 'Depression'), ('PTSD', 'Post-Traumatic Stress Disoder (PTSD)'), ('Personality', 'Personality Disorders'), ('Sexual', 'Sexual Disorders'), ('General', 'General'), ('Undiagnosed', 'Undiagnosed')], default='Undiagnosed', max_length=12)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
